### ISSUE TITLE
Props Exercice suggestions

### ISSUE THREAD

**Issue by ldealmei** [HackYourFutureBelgium/React#67]
1. It might be interesting to ask as a bonus to get rid of the warning : `Warning: Each child in a list should have a unique "key" prop.`

2. I am not sure I understand the purpose of `Passing functions as props` and `Passing functions as props: part 2`. I understand that it demonstrates that we can also pass functions as arguments but I'm not too sure what is expected from the student.

**Comment by Toinne** [comment]
1. Added https://github.com/HackYourFutureBelgium/React/commit/62e60f4b9ddebf0a06f1b8ee658afcc69d7b8262

2. For 2 made that piece of code a bit complicated with the reduced array etc.
The purpose of the exercise was more to try and figure out what was going on.
https://github.com/HackYourFutureBelgium/React/commit/baa9907f80444de26e2d47dea81febea212da727
